<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pregunta extends \App\Entity\Pregunta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'idpregunta', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'parametromedicion', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'rojo', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'amarillo', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'verde', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'fecha'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'idpregunta', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'parametromedicion', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'rojo', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'amarillo', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'verde', '' . "\0" . 'App\\Entity\\Pregunta' . "\0" . 'fecha'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pregunta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdpregunta(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpregunta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpregunta', []);

        return parent::getIdpregunta();
    }

    /**
     * {@inheritDoc}
     */
    public function getParametromedicion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParametromedicion', []);

        return parent::getParametromedicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setParametromedicion(?string $parametromedicion): \App\Entity\Pregunta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParametromedicion', [$parametromedicion]);

        return parent::setParametromedicion($parametromedicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRojo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRojo', []);

        return parent::getRojo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRojo(?string $rojo): \App\Entity\Pregunta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRojo', [$rojo]);

        return parent::setRojo($rojo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmarillo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmarillo', []);

        return parent::getAmarillo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmarillo(?string $amarillo): \App\Entity\Pregunta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmarillo', [$amarillo]);

        return parent::setAmarillo($amarillo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerde(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerde', []);

        return parent::getVerde();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerde(?string $verde): \App\Entity\Pregunta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerde', [$verde]);

        return parent::setVerde($verde);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(?\DateTimeInterface $fecha): \App\Entity\Pregunta
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

}
