<?php

namespace ContainerZa7pg4x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPregunta2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R8mhXAN.App\Entity\Pregunta' shared service.
     *
     * @return \App\Entity\Pregunta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R8mhXAN": it references class "App\\Entity\\Pregunta" but no such service exists.');
    }
}
