<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMi7brm8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMi7brm8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMi7brm8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMi7brm8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMi7brm8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mi7brm8',
    'container.build_id' => 'f7862983',
    'container.build_time' => 1652456183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMi7brm8');
