<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQcJtWH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQcJtWH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQcJtWH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQcJtWH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIQcJtWH\App_KernelDevDebugContainer([
    'container.build_hash' => 'IQcJtWH',
    'container.build_id' => '30314593',
    'container.build_time' => 1656680178,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQcJtWH');
