<?php

namespace ContainerGDDm0Oa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RAR87DkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rAR87Dk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rAR87Dk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'respuestum' => ['privates', '.errored..service_locator.rAR87Dk.App\\Entity\\Respuesta', NULL, 'Cannot autowire service ".service_locator.rAR87Dk": it references class "App\\Entity\\Respuesta" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'respuestum' => 'App\\Entity\\Respuesta',
        ]);
    }
}
