<?php

namespace ContainerGDDm0Oa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KZg2ncMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kZg2ncM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kZg2ncM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IndexController::cuestionario' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController::delete' => ['privates', '.service_locator.OZGTtK2', 'get_ServiceLocator_OZGTtK2Service', true],
            'App\\Controller\\PreguntaController::edit' => ['privates', '.service_locator.OZGTtK2', 'get_ServiceLocator_OZGTtK2Service', true],
            'App\\Controller\\PreguntaController::index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController::show' => ['privates', '.service_locator.R8mhXAN', 'get_ServiceLocator_R8mhXANService', true],
            'App\\Controller\\RespuestaController::delete' => ['privates', '.service_locator.rAR87Dk', 'get_ServiceLocator_RAR87DkService', true],
            'App\\Controller\\RespuestaController::edit' => ['privates', '.service_locator.rAR87Dk', 'get_ServiceLocator_RAR87DkService', true],
            'App\\Controller\\RespuestaController::index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RespuestaController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RespuestaController::show' => ['privates', '.service_locator.JpCNm0Q', 'get_ServiceLocator_JpCNm0QService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\IndexController:cuestionario' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController:delete' => ['privates', '.service_locator.OZGTtK2', 'get_ServiceLocator_OZGTtK2Service', true],
            'App\\Controller\\PreguntaController:edit' => ['privates', '.service_locator.OZGTtK2', 'get_ServiceLocator_OZGTtK2Service', true],
            'App\\Controller\\PreguntaController:index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\PreguntaController:show' => ['privates', '.service_locator.R8mhXAN', 'get_ServiceLocator_R8mhXANService', true],
            'App\\Controller\\RespuestaController:delete' => ['privates', '.service_locator.rAR87Dk', 'get_ServiceLocator_RAR87DkService', true],
            'App\\Controller\\RespuestaController:edit' => ['privates', '.service_locator.rAR87Dk', 'get_ServiceLocator_RAR87DkService', true],
            'App\\Controller\\RespuestaController:index' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RespuestaController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\RespuestaController:show' => ['privates', '.service_locator.JpCNm0Q', 'get_ServiceLocator_JpCNm0QService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\IndexController::cuestionario' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\PreguntaController::delete' => '?',
            'App\\Controller\\PreguntaController::edit' => '?',
            'App\\Controller\\PreguntaController::index' => '?',
            'App\\Controller\\PreguntaController::new' => '?',
            'App\\Controller\\PreguntaController::show' => '?',
            'App\\Controller\\RespuestaController::delete' => '?',
            'App\\Controller\\RespuestaController::edit' => '?',
            'App\\Controller\\RespuestaController::index' => '?',
            'App\\Controller\\RespuestaController::new' => '?',
            'App\\Controller\\RespuestaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\IndexController:cuestionario' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\PreguntaController:delete' => '?',
            'App\\Controller\\PreguntaController:edit' => '?',
            'App\\Controller\\PreguntaController:index' => '?',
            'App\\Controller\\PreguntaController:new' => '?',
            'App\\Controller\\PreguntaController:show' => '?',
            'App\\Controller\\RespuestaController:delete' => '?',
            'App\\Controller\\RespuestaController:edit' => '?',
            'App\\Controller\\RespuestaController:index' => '?',
            'App\\Controller\\RespuestaController:new' => '?',
            'App\\Controller\\RespuestaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
