<?php

namespace ContainerGDDm0Oa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OZGTtK2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OZGTtK2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OZGTtK2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'preguntum' => ['privates', '.errored..service_locator.OZGTtK2.App\\Entity\\Pregunta', NULL, 'Cannot autowire service ".service_locator.OZGTtK2": it references class "App\\Entity\\Pregunta" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'preguntum' => 'App\\Entity\\Pregunta',
        ]);
    }
}
