<?php

namespace ContainerGDDm0Oa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreguntaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PreguntaType' shared autowired service.
     *
     * @return \App\Form\PreguntaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PreguntaType.php';

        return $container->privates['App\\Form\\PreguntaType'] = new \App\Form\PreguntaType();
    }
}
